### ISSUE TITLE
Dynamic fontfaces

### ISSUE THREAD

**Issue by lpsandaruwan** [mooniak/fontpad#2]
Hi,

Can we load font faces dynamically in runtime? :-)

**Comment by pathumego** [comment]
From a json feed? Kind of like https://github.com/akuru/fontester?

**Comment by lpsandaruwan** [comment]
Exactly. :+1:

**Comment by THPubs** [comment]
Hmm... Load fonts dynamically to show multiple fonts in one page or to let people change the font in a block? Might need to have a skype meeting to discuss this and issue #4  :smile_cat:

**Comment by lpsandaruwan** [comment]
I think this issue is now irrelevant, what I wanted to do is including Fontpad in Fonman. After the first discussion we had I did tend to use an alternative solution. Sorry I didn't notice that this issue has not being closed. :-)

**Comment by THPubs** [comment]
Haha no issue :-)
